### ISSUE TITLE
Que projeto excepcional

### ISSUE THREAD

**Issue by cHIsIMun** [samuel-cavalcanti/teddy_bear_filter#1]
Olá, gostaria de saber mais algumas informações sobre o dataset que utilizou pra treinar, aparentemente o mesmo não está mais disponível no kaggle o que me entristece um pouco, parece ter sido um dataset bem construido. No mais espero que seu projeto ganhe a visibilidade que merece, belo trabalho!

**Comment by samuel-cavalcanti** [comment]
Olá lucas obrigado. Infelizmente eu não tenho mais o dataset. Sobre o conjunto de dados encontrei esse notebook que faz um estudo sobre ele: https://www.kaggle.com/code/amansingh29/parental-advisory-explicit-insights/notebook
